select distinct BENEFITINFO from ELIGIBILITYBENEFIT fetch first 10 rows only; -- eb01
select distinct COVERAGELEVEL from ELIGIBILITYBENEFIT fetch first 10 rows only; -- eb02
select distinct SERVICETYPECODE from ELIGIBILITYBENEFIT fetch first 10 rows only; -- eb03
select distinct INSURANCETYPE from ELIGIBILITYBENEFIT fetch first 10 rows only; -- eb04
select distinct PLANCOVERAGEDESC from ELIGIBILITYBENEFIT fetch first 10 rows only; -- eb05
select distinct TIMEPERIODTYPE from ELIGIBILITYBENEFIT fetch first 10 rows only; -- eb06
select distinct MONETARYAMOUNT from ELIGIBILITYBENEFIT fetch first 10 rows only; -- eb07
select distinct PERCENTAGE from ELIGIBILITYBENEFIT fetch first 10 rows only; -- eb08
select distinct QUANTITYTYPE from ELIGIBILITYBENEFIT fetch first 10 rows only; -- eb09
select distinct QUANTITY from ELIGIBILITYBENEFIT fetch first 10 rows only; -- eb10
select distinct AUTHORIZATIONREQ from ELIGIBILITYBENEFIT fetch first 10 rows only; -- eb11
select distinct PLANNETWORK from ELIGIBILITYBENEFIT fetch first 10 rows only; -- eb12
select distinct MEDICALPROCEDURE from ELIGIBILITYBENEFIT fetch first 10 rows only; -- eb13
select distinct DIAGNOSIS from ELIGIBILITYBENEFIT fetch first 10 rows only; -- eb14
