-- get name from id
select NAME
from INSURANCEPACKAGE
where ID = 982;

-- get id from name
select ID, NAME
from INSURANCEPACKAGE
where NAME = 'MEDICARE'
order by ID, NAME
    fetch first 20 rows only
;

-- get package name from patient
select PATIENTINSURANCE.ID as PIID,
       PATIENTINSURANCE.SEQUENCENUMBER,
       INSURANCEPACKAGE.ID as IPID,
       INSURANCEPACKAGE.NAME
from INSURANCEPACKAGE
         inner join PATIENTINSURANCE on PATIENTINSURANCE.INSURANCEPACKAGEID = INSURANCEPACKAGE.ID
where PATIENTINSURANCE.PATIENTID = 1561424
  and PATIENTINSURANCE.CANCELLED is null
  and PATIENTINSURANCE.DELETED is null
;

-- get long package name patient
select
PATIENTINSURANCE.PATIENTID, PATIENTINSURANCE.SEQUENCENUMBER,
length(INSURANCEPACKAGE.NAME)
from INSURANCEPACKAGE
inner join PATIENTINSURANCE on PATIENTINSURANCE.INSURANCEPACKAGEID = INSURANCEPACKAGE.ID
where PATIENTINSURANCE.CANCELLED is null and PATIENTINSURANCE.DELETED is null
order by length(INSURANCEPACKAGE.NAME) desc
fetch first 10 rows only
;
