-- get empty tracks
select INS.PATIENTID, INS.ID, INS.SEQUENCENUMBER, PACKAGE.NAME
from PATIENTINSURANCE INS
left join ELIGIBILITYTRACK TRACK on TRACK.PATIENTINSURANCEID = INS.ID
inner join INSURANCEPACKAGE PACKAGE on PACKAGE.ID = INS.INSURANCEPACKAGEID
where TRACK.PATIENTINSURANCEID is null
and INS.CANCELLED is null
and INS.DELETED is null
and PACKAGE.NAME = 'UNITED HEALTHCARE'
order by INS.CREATED desc
fetch first 10 rows only
;
